server:
  shutdown: graceful

spring:
    lifecycle:
        timeout-per-shutdown-phase: 30s

debezium:
  config-properties: |
    name=mysql-dbz-connector
    connector.class=io.debezium.connector.mysql.MySqlConnector
    offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
    offset.storage.file.filename=data/offset.data
    offset.flush.interval.ms=0
    database.hostname=127.0.0.1
    database.port=34306
    database.user=canal
    database.password=canal
    database.server.id=85747
    #table.exclude.list
    table.include.list=mytest2.*
    #database.initial.statements
    snapshot.mode=schema_only
    #The 'snapshot.mode' value is invalid: Value must be one of always, never, initial_only, configuration_based, when_needed, initial, custom, schema_only, no_data, recovery, schema_only_recovery
    include.schema.changes=true
    include.query=true
    database.include.list=mytest2
    topic.prefix=test
    schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
    schema.history.internal.file.filename=data/schemahistory.data
    #transforms=unwrap
    #transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
    #transforms.unwrap.drop.tombstones=false
    max.batch.size=2048
    max.queue.size=8192
    #max.batch.size default 2048
    #max.queue.size default 8192
logging:
  level:
    io:
      debezium: info
    root: info